In [34]:
import torch
import numpy as np

#### Initializing a Tensor

In [35]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [36]:
np_array= np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [37]:
x_ones = torch.ones_like(x_data)  # input 값과 동일한 크기의 1로 채워진 배열 반환
print(f'Ones Tensor: \n {x_ones} \n')

x_rand = torch.rand_like(x_data, dtype=torch.float)  # input 값과 동일한 크기의 [0, 1) 사이의 랜덤한 값으로 채워진 배열 반환
print(f'Random Tensor: \n {x_rand} \n')

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4043, 0.5221],
        [0.5749, 0.3054]]) 



In [38]:
shape = (2, 3, )  # 해당 예제에서는 (2, 3)으로 정의해도 무방
rand_tensor = torch.rand(shape)  # shape의 형태를 가지고 [0, 1) 사이의 랜덤한 값으로 채워진 배열 반환
ones_tensor = torch.ones(shape)  # shape의 형태를 가지고 1로 채워진 배열 반환
zeros_tensor = torch.zeros(shape)  # shape의 형태를 가지고 0으로 채워진 배열 반환

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4697, 0.8811, 0.0134],
        [0.5852, 0.0852, 0.9332]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


#### Attributes of a Tensor

In [39]:
ts = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 3])
Datatype of tensor: torch.int64
Device tensor is stored on: cpu


In [40]:
if torch.cuda.is_available():
    ts = tensor.to("cuda")  # tensor는 기본적으로 CPU에서 생성되고, .to를 사용하여 cuda, gpu에서 사용되도록 변경 가능
    # 딥러닝 알고리즘은 많은 양의 단순 사칙연산을 수행하는데, 이를 병렬화하여 수행하기 위해 GPU를 활용하는 것

In [76]:
ts = torch.ones(4, 4)
print(f"First row: {ts[0]}")
print(f"First column: {ts[:, 0]}")
print(f"Last column: {ts[..., -1]}")
ts[:,1] = 0  # 1번째 열을 0으로 변경
print(ts)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [77]:
t1 = torch.cat([ts, ts, ts], dim=1)  # cat은 tensor를 가로로 연결
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [80]:
# 3가지 수식은 행렬 곱을 의미하며, y1, y2, y3는 동일한 값을 가진다.
# ts.T 는 전치행렬을 반환한다. 전치행렬 링크: https://en.wikipedia.org/wiki/Transpose

y1 = ts @ ts.T
y2 = ts.matmul(ts.T)

y3 = torch.rand_like(y1)
torch.matmul(ts, ts.T, out=y3)  # ts와 ts.T의 행렬곱을 y3에 저장

# 3가지 수식은 element-wise product를 의미, element-wise product 링크: https://en.wikipedia.org/wiki/Hadamard_product_(matrices)
# element_wise product는 동일한 형태를 가진 배열들로 구성되며, 동일한 형태의 배열을 반환
# 원소간의 곱을 나타낸다. 링크를 확인하면 충분히 이해할 수 있음
# z1, z2, z3는 동일한 값을 가진다.

z1 = ts * ts
z2 = ts.mul(ts)

z3 = torch.rand_like(ts)
torch.mul(ts, ts, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [83]:
agg = ts.sum()
print(agg)
agg_item = agg.item()  # one-element tensor, 즉 tensor 내에 값이 하나만 존재하는 경우 .item()을 활용하여 숫자로 변환할 수 있다.
print(agg_item, type(agg_item))

tensor(12.)
12.0 <class 'float'>


In [84]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


#### Bridge with NumPy

In [86]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [87]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")
# tensor의 변화가 numpy array에도 적용된다

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [88]:
n = np.ones(5)
t = torch.from_numpy(n)

In [89]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")
# 마찬가지로 numpy array의 변화가 tensor에도 적용된다

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
